version: '2'
services:
  db:
    image: postgres
    environment:
      - POSTGRES_USER=pulp
      - POSTGRES_PASSWORD=pulp
    ports:
      - '127.0.0.1:5432:5432'
    volumes:
      - ./.volume/postgres:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "pulp" ]
  redis:
    image: redis
    ports:
      - '127.0.0.1:6379:6379'
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
  api:
    image: pulp-api
    env_file: .env
    depends_on:
      db: { condition: service_healthy }
      redis: { condition: service_healthy }
    ports:
      - '24817:24817'
    volumes:
      - ./.volume/pulp:/var/lib/pulp
    healthcheck:
      test: [ "CMD", "curl", "--fail", "http://localhost:24817/pulp/api/v3/status/" ]
  content:
    image: pulp-content
    env_file: .env
    depends_on:
      db: { condition: service_healthy }
      api: { condition: service_healthy }
    ports:
      - '24816:24816'
    volumes:
      - ./.volume/pulp:/var/lib/pulp
  resource-manager:
    image: pulp-resource-manager
    env_file: .env
    depends_on:
      db: { condition: service_healthy }
      api: { condition: service_healthy }
      redis: { condition: service_healthy }
    volumes:
      - ./.volume/pulp:/var/lib/pulp
  worker:
    image: pulp-worker
    env_file: .env
    depends_on:
      db: { condition: service_healthy }
      api: { condition: service_healthy }
      redis: { condition: service_healthy }
    volumes:
      - ./.volume/pulp:/var/lib/pulp
